server:
  port: 9527

spring:
  application:
    name: nacos-gateway
  redis:
    timeout: 5000
    # redis-single
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
#    sentinel:
#      # 取消控制台懒加载
#      eager: true
#      transport:
#        #配置Sentinel dashboard地址
#        dashboard: localhost:7000
#        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
#        port: 8719
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: user_routes
          uri: lb://user-service
          predicates:
            Path=/user/** #断言,路径相匹配的进行路由

        - id: product_routes
          uri: lb://product-service
          predicates:
            Path=/product/** #断言,路径相匹配的进行路由

        - id: order_routes
          uri: lb://order-service
          predicates:
           Path=/order/** #断言,路径相匹配的进行路由

        - id: pay_routes
          uri: lb://order-service
          predicates:
            Path=/pay/** #断言,路径相匹配的进行路由

        - id: rabbitMQ_routes
          uri: lb://rabbitMQ-msg-sender
          predicates:
            Path=/amqp/** #断言,路径相匹配的进行路由

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

