server:
  port: 4101


spring:
  application:
    name: rabbitMQ-msg-sender
  redis:
    timeout: 5000
    # redis-single
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
