server:
  port: 8001

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      eager: true
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:7000
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-ds1-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  user-duration: http://user-duration
